### ISSUE TITLE
golang/go not updated

### ISSUE THREAD

**Issue by frezbo** [aquaproj/aqua-renovate-config#189]
Go 1.19 was released on 2nd Aug, 2022, but it seems I didn't get a renovate PR for the same.

The renovate config clearly sees the deps [here](https://github.com/frezbo/dotfiles/issues/2):

![image](https://user-images.githubusercontent.com/18496730/182622794-037193b5-be82-4673-b2d0-e2d8442abe0e.png)
seems something got broken recently. Creating it here to track why some deps doesn't gets updated. Had a similar issue with goimports as referenced in #185

**Comment by frezbo** [comment]
Seems renovate has failed to update go in aqua-registry too: https://github.com/aquaproj/aqua-registry/tree/main/pkgs/golang/go

**Comment by suzuki-shunsuke** [comment]
https://github.com/renovatebot/renovate/issues/16933

**Comment by suzuki-shunsuke** [comment]
Thank you for your report.

**Comment by frezbo** [comment]
I'll try to see what's broken when I get some time, seems renovate is a bit flaky this week

**Comment by suzuki-shunsuke** [comment]
Thank you. Recently I'm a little busy so it is difficult to investigate the issue about Renovate for now.

**Comment by suzuki-shunsuke** [comment]
Related tweet (Japanese).
https://twitter.com/ponkio_o/status/1555048136825262081

**Comment by suzuki-shunsuke** [comment]
Maybe this warning is about `go` datasource?
https://github.com/aquaproj/aqua-renovate-config/pull/177
https://github.com/aquaproj/aqua-renovate-config/blob/c151d1037840fc9c3a1e7915c2a5ce1736fa714b/default.json#L95-L102

**Comment by suzuki-shunsuke** [comment]
I guess we can ignore this warning although we would like to remove the warning.
aqua-renovate-config's default preset uses two datasources, `github_release` datasource and `go` datasource.

Renovate tries to get each package's version from these datasources, but Renovate can get the version from only one datasource.

For example, Renovate would succeed to get the version of `suzuki-shunsuke/tfcmt` from `github_release` datasource
but would fail to get it from `go` datasource.
This failure would be shown as the warning, but I guess we can ignore this warning.

Note that the above description is just my assumption.

**Comment by suzuki-shunsuke** [comment]
Hmm...
Maybe we can distinguish the datasource by the regular expression of package name.

`go` datasource package name includes a period `.`.

```
pkgs/golang.org/x/tools/cmd/goimports/registry.yaml
2:  - type: go_install
3-    name: golang.org/x/tools/cmd/goimports
4-    path: golang.org/x/tools/cmd/goimports
5-    repo_owner: golang
6-    repo_name: tools
7-    version_source: github_tag

pkgs/golang.org/x/tools/gopls/registry.yaml
2:  - type: go_install
3-    name: golang.org/x/tools/gopls
4-    aliases:
5-      - name: golang/tools/gopls
6-    path: golang.org/x/tools/gopls
7-    repo_owner: golang

pkgs/golang.org/x/perf/cmd/benchstat/registry.yaml
2:  - type: go_install
3-    path: golang.org/x/perf/cmd/benchstat
4-    description: Benchstat computes and compares statistics about benchmarks
5-    link: https://pkg.go.dev/golang.org/x/perf/cmd/benchstat
6-
```

**Comment by suzuki-shunsuke** [comment]
https://github.com/aquaproj/aqua-renovate-config/pull/192

**Comment by suzuki-shunsuke** [comment]
Released. https://github.com/aquaproj/aqua-renovate-config/releases/tag/1.2.1

**Comment by suzuki-shunsuke** [comment]
golang/go was updated from 1.18.4 to 1.18.5, but not updated to 1.19.
https://github.com/suzuki-shunsuke/test-renovate/pull/158

I guess this is because `1.19` is invalid as semver.
When `go1.19.x` will be released, Renovate would update golang/go.

**Comment by suzuki-shunsuke** [comment]
Renovate supports various versioning, but I don't know which is best for `golang/go`.
https://docs.renovatebot.com/modules/versioning/

**Comment by frezbo** [comment]
> golang/go was updated from 1.18.4 to 1.18.5, but not updated to 1.19.

yeh, i guess that's right, i manually updated for now.

**Comment by frezbo** [comment]
I'm closing this issue for now, since this is a minor inconvenience.

**Comment by frezbo** [comment]
Thanks for chasing the issue and putting up a fix :+1:

**Comment by rust84** [comment]
I tried semver-coerced with no luck and ended up just setting it to loose. 

```
  "packageRules": [
    {
      "matchDatasources": ["github-tags"],
      "matchPackageNames": ["golang/go"],
      "versioning": "loose"
    }
  ]
```
