### ISSUE TITLE
 Dependency Lookup Warnings in `aqua.yaml`

### ISSUE THREAD

**Issue by ponkio-o** [aquaproj/aqua-renovate-config#194]
related: https://github.com/aquaproj/aqua-renovate-config/issues/189

Hi @suzuki-shunsuke , thnak you for develop great tool!

I have imported the [recently released version](https://github.com/aquaproj/aqua-renovate-config/releases/tag/1.2.1) of aqua-renovate-config, but I get a warning about `aqua.yaml`
https://github.com/ponkio-o/dotfiles/issues/14
![image](https://user-images.githubusercontent.com/29038315/183015064-2acbc7a9-9247-49d6-99d0-d4267f75c5f3.png)

Am I missing something?

**Comment by suzuki-shunsuke** [comment]
Thank you for your report.
I'll fix the warning.
https://github.com/aquaproj/aqua-renovate-config/pull/195

**Comment by suzuki-shunsuke** [comment]
Released. https://github.com/aquaproj/aqua-renovate-config/releases/tag/1.2.2

**Comment by ponkio-o** [comment]
Thank you for your quickly reply and release!! I have confirmed that it has been successfully fixed.

https://github.com/ponkio-o/dotfiles/issues/14
![image](https://user-images.githubusercontent.com/29038315/183040799-b63a009c-cbb9-425b-ab2c-1c778f16a401.png)
