### ISSUE TITLE
[Q] why does Renovate create a wrong PR for one single tool?

### ISSUE THREAD

**Issue by CrystalMethod** [aquaproj/aqua-renovate-config#375]
* I'm using Aqua to maintain the tooling on my different laptops
* I've installed the Renovate app which takes care of updating versions
* I'm using Chezmoi for managing dotfiles across different platforms (should not be the cause for my problem)

https://github.com/CrystalMethod/dotfiles

I'm using `datree` for policy management and enforcement in my Kubernetes environments.

https://github.com/CrystalMethod/dotfiles/blob/6215b4ec9ab3aa820acfd8007cc18267c1d30790/private_dot_config/private_aqua/aqua.yaml.tmpl#LL31

Since installing `datree` version 1.8.33 there where several updates and current version is 1.8.39. So there is a PR generated by Renovate.

https://github.com/CrystalMethod/dotfiles/pull/249

But the PR would insert prefix "v", so `1.8.33` would become `v1.8.39`. Aqua wouldn't be able to install `datree/datree@v1.8.39`. See the package definition in "standard" Aqua registry.

https://github.com/aquaproj/aqua-registry/blob/b4c9b5f6638d3103121a64c46d88cd5a8f56bb9b/pkgs/datreeio/datree/pkg.yaml#L2

So my question is: why does Renovate generates a wrong PR for this single tool?

If you look at the history of PRs, you can see that this has been going on for quite a while.

**Comment by suzuki-shunsuke** [comment]
I can't reproduce the issue.

- https://github.com/suzuki-shunsuke/test-renovate/pull/213
- https://github.com/suzuki-shunsuke/test-renovate/tree/9e5ccbe5e56b3980845cf004b197193a8eefc45c

How about checking the log of Renovate?

<details>
<summary>My Renovate log</summary>

```json
      {
        "datasourceTemplate": "github-releases",
        "deps": [
          {
            "currentValue": "1.8.33",
            "currentVersion": "1.8.33",
            "datasource": "github-releases",
            "depName": "datreeio/datree",
            "fixedVersion": "1.8.33",
            "isSingleVersion": true,
            "packageName": "datreeio/datree",
            "registryUrl": "https://github.com",
            "replaceString": " name: datreeio/datree@1.8.33",
            "sourceUrl": "https://github.com/datreeio/datree",
            "versioning": "semver",
            "warnings": [],
            "updates": [
              {
                "bucket": "non-major",
                "newVersion": "1.8.41",
                "newValue": "1.8.41",
                "releaseTimestamp": "2023-03-15T08:53:01.000Z",
                "newMajor": 1,
                "newMinor": 8,
                "updateType": "patch",
                "branchName": "renovate/datreeio-datree-1.x"
              }
            ]
          }
        ],
        "matchStrings": [
          " +(?:version|'version'|\"version\") *: +(?<currentValue>[^'\" \\n]+) +# renovate: depName=(?<depName>(?<packageName>[^'\" .@/\\n]+/[^'\" @/\\n]+)(/[^'\" /@\\n]+)*)",
          " +(?:version|'version'|\"version\") *: +'(?<currentValue>[^'\" \\n]+)' +# renovate: depName=(?<depName>(?<packageName>[^'\" .@/\\n]+/[^'\" @/\\n]+)(/[^'\" /@\\n]+)*)",
          " +(?:version|'version'|\"version\") *: +\"(?<currentValue>[^'\" \\n]+)\" +# renovate: depName=(?<depName>(?<packageName>[^'\" .@/\\n]+/[^'\" @/\\n]+)(/[^'\" /@\\n]+)*)",
          " +(?:name|'name'|\"name\") *: +(?<depName>(?<packageName>[^'\" .@/\\n]+/[^'\" @/\\n]+)(/[^'\" /@\\n]+)*)@(?<currentValue>[^'\" \\n]+)",
          " +(?:name|'name'|\"name\") *: +'(?<depName>(?<packageName>[^'\" .@/\\n]+/[^'\" @/\\n]+)(/[^'\" /@\\n]+)*)@(?<currentValue>[^'\" \\n]+)'",
          " +(?:name|'name'|\"name\") *: +\"(?<depName>(?<packageName>[^'\" .@/\\n]+/[^'\" @/\\n]+)(/[^'\" /@\\n]+)*)@(?<currentValue>[^'\" \\n]+)\""
        ],
        "packageFile": "aqua.yaml"
      },
```

</details>

I have two hypotheses.

1. Renovate was something wrong temporarily
1. a Release `v1.8.39` was created accidentally and was removed

How about recreating a pull request by Renovate? If you rename and close the pull request, Renovate will recreate a pull request.
I guess this is a temporal issue.

**Comment by suzuki-shunsuke** [comment]
I don't think this is an issue of aqua and aqua-renovate-config.
You can ask the support from the Renovate community if necessary.

https://github.com/renovatebot/renovate/discussions

If you ask the support from the Renovate community, you should prepare minimum reproduction code and repository.

https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md
