### ISSUE TITLE
Support updating aqua-renovate-config in config preset(default.json)

### ISSUE THREAD

**Issue by mikutas** [aquaproj/aqua-renovate-config#448]
For now updating aqua-renovate-config in `default.json` isn't supported.
`default.json` is recommended filename of [config presets](https://docs.renovatebot.com/config-presets/).

**Comment by suzuki-shunsuke** [comment]
- https://github.com/aquaproj/aqua-renovate-config/pull/449
- https://github.com/aquaproj/aqua-renovate-config/pull/450
- https://github.com/aquaproj/aquaproj.github.io/pull/695

**Comment by suzuki-shunsuke** [comment]
1.13.0 is out 🎉
https://github.com/aquaproj/aqua-renovate-config/releases/tag/1.13.0

**Comment by suzuki-shunsuke** [comment]
It works well.

- https://github.com/suzuki-shunsuke/test-renovate/pull/239
